#!/bin/bash

SHARED_PATH="/usr/share/nova/sharedFiles"
MAIN_PATH="$SHARED_PATH/Quasar/main.js"
MODULE_PATH="$SHARED_PATH/NodejsModule"

cd "$SHARED_PATH/Quasar"

if (($# == 1)); then
	if [[ "$1" == "--debug" ]] || [[ "$1" == "-d" ]]; then
		echo "Debug mode: Running quasar without forever"
		NODE_PATH="$MODULE_PATH" node $MAIN_PATH
		exit
	else
		echo "Unknown arguement. Usage: quasar [-d (--debug)]"
		echo "  -d (--debug) Run node directly and show output in stdout instead of using forever to daemonize."
		exit
	fi
fi

echo "Starting quasar with the forever daemon"
NODE_PATH="$MODULE_PATH" forever start $MAIN_PATH
exit

