.TH QUASAR "1" "2013" "12.12"

.SH NAME 
.B quasar
\- A Web Based frontend for Nova

.SH SYNOPSIS 
.B quasar

.SH DESCRIPTION 
.PP 
.I quasar 
is the web interface frontend for monitoring and configuring the NOVA system. It can be accessed via HTTPS on port 8080 by default (with the username 'nova' and the password 'toor'). Configuration of NOVA can be done via this web front end, and this will eventially replace the QT interface 
.B quasar

.TP
-d (--debug)
Instead of launching with the forever tool as a daemon, launches with a blocking call and shows output in stdout.

.SH SEE ALSO 
.B novad(1), 
.B novacli(1), 
.B honeyd(1)

.SH COPYRIGHT 
.PP 
.B Nova is Copyright (c) 2011 - 2013 DataSoft Corporation
.PP 
Nova is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. Nova is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with Nova.  If not, see <http://www.gnu.org/licenses/>.
